# Generated by Django 5.0.4 on 2024-09-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=10)),
                ('received_date', models.DateField()),
                ('inventory_received', models.CharField(max_length=100)),
                ('reported_issues', models.TextField()),
                ('client_notes', models.TextField()),
                ('assigned_technician', models.CharField(max_length=100)),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('actions', models.CharField(max_length=100)),
            ],
        ),
    ]
